trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: 'GitHub PATS'

steps:
  - checkout: self
    persistCredentials: true
    fetchDepth: 0

  - script: |
      git config --global user.email "devops-mirror@bytecourier.com"
      git config --global user.name "Azure DevOps Mirror"

      git remote add github https://$(RAG_AGENT_CHATBOT_PAT)@github.com/devgig/rag-agent-chatbot.git

      git push github --all
      git push github --tags
    displayName: 'Mirror to GitHub'
    env:
      RAG_AGENT_CHATBOT_PAT: $(rag-agent-chatbot-pat)
