apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend-env-configmap.yaml

# Add ConfigMap to deployment as environment variables
# Assumes your deployment is named 'multi-agent-frontend'
configurations:
  - kustomizeconfig.yaml
