apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Frontend
  - frontend-deployment.yaml
  - frontend-service.yaml
  - frontend-env-configmap.yaml
  # Backend
  - backend-deployment.yaml
  - backend-service.yaml
  # Model inference
  - gpt-oss-120b-deployment.yaml
  # Istio routing
  - istio-httproute.yaml
  - backend-httproute.yaml
